version: '3.5'

services:
  
  nifi:
    image: apache/nifi:latest
    # build: ./nifi
    container_name: nifi
    restart: 'no'
    user: root
    ports:
      - 8443:8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes:
      - ./nifi/conf/:/opt/nifi/nifi-current/conf/
      - nifi_python:/opt/nifi/nifi-current/datos_out/
    
    env_file:
      - .env
    
  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifiregistry
    restart: 'no'
    ports:
      - 18080:18080
    
    env_file:
      - .env
  
  
  
  
  
  postgres:
    container_name: postgres_container
    build: ./postgres 
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      POSTGRES_DB: idealista
      PGDATA: /data/postgres
    
    depends_on:
      - nifi

    env_file:
      - .env
    
    volumes:
      - postgres:/data/postgres
      - ./postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql    
    ports:
      - "5432:5432"

    
    networks: 
      - postgres
      
    
    restart: unless-stopped

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4:4.16
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    
  #   volumes:
  #     - pgadmin:/root/.pgadmin

  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"

  #   networks:
  #     - postgres

  #   restart: unless-stopped


  python:
    container_name: python_main
    build: ./python

    volumes:
      - nifi_python:/datos/datos_ini/
      - db_barrios:/datos/datos_out/
      


    restart: 'no'
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - postgres


  jupyter:
    container_name: jupyter_notebook
    build: ./jupyter

    depends_on:
      - postgres
    ports:
      - 10000:8888

    volumes:
      - db_barrios:/home/jovyan/work/datos/datos_out/
  

networks:
  postgres:
    external: false
    name: postgres
    driver: bridge

volumes:
  postgres:
  db_barrios:
  nifi_python:
  # pgadmin: