FROM apache/nifi:latest

# Copiamos start.sh con las opciones que hemos definido por defecto (después de la linea #### MIMOVE ####) para poder
# ejecutar automáticamente NiFi con el flujo que hemos creado para descargar los archivos de OpenData Valencia

COPY ./start.sh /opt/nifi/scripts

