FROM apache/nifi:latest

RUN mkdir -p /tmp/out/

# RUN chown -R admin:admin /tmp
RUN chmod 755 /tmp/out/
# USER admin
# COPY ./conf/ /opt/nifi/nifi-current/
# COPY ./flow.json.gz /opt/nifi/nifi-current/conf/
# COPY ./nifi.properties /opt/nifi/nifi-current/conf/

